name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '5.0.x'
          
      - name: .NET Restore
        run: dotnet restore
        
      #- name: .NET Build
      #  run: dotnet build --configuration Release --no-restore
          
      - name: Publish .NET Core Project
        run: dotnet publish GitHubPages.Web/GitHubPages.Web.csproj -c Release -o release --nologo
        
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
        
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot 
        
